---
version: '3'
services:

# START SERVICE nginx.rewrite
  nginx:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.nginx.rewrite:1.17.3
    environment: ['CONTECO_NGINX_CONF_LOCATION=/package/ekg/elasticsearch', 'CONTECO_NGINX_CONF_PROXY_PASS=package_ekg_elasticsearch:9200']
    command: []
    volumes: []
    ports: []
    networks: [modeco_overlay, package_overlay]
    deploy:
      mode: replicated
      replicas: ${EKG_REST_ELASTICSEARCH_DEPLOY_REPLICAS}
      resources:
        limits:
          cpus: '${EKG_REST_ELASTICSEARCH_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${EKG_REST_ELASTICSEARCH_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${EKG_REST_ELASTICSEARCH_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${EKG_REST_ELASTICSEARCH_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      placement:
        constraints: [${EKG_REST_ELASTICSEARCH_DEPLOY_PLACEMENT_CONSTRAINTS}]
      labels: [traefik.enable=true,traefik.docker.network=modeco_overlay, traefik.http.services.package_ekg_elasticsearch.loadbalancer.server.port=80, traefik.http.routers.package_ekg_elasticsearch.entrypoints=conteco, traefik.http.routers.package_ekg_elasticsearch.rule=PathPrefix("/package/ekg/elasticsearch")]
    labels: [${EKG_REST_ELASTICSEARCH_LABELS}]
# END SERVICE nginx.rewrite

volumes: {}
networks: {modeco_overlay: { external: true }, package_overlay: { external: true }}
