---
version: '3'
services:

# START SERVICE nginx.rewrite
  nginx:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM}/${CONTECO_ECOSYSTEM}.nginx.rewrite:1.17.3
    environment: ['CONTECO_NGINX_CONF_LOCATION=/package/ekg/grafana', 'CONTECO_NGINX_CONF_PROXY_PASS=package_ekg_grafana:3000']
    command: []
    volumes: []
    ports: []
    networks: [modeco_overlay, package_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: '${EKG_UI_GRAFANA_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${EKG_UI_GRAFANA_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${EKG_UI_GRAFANA_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${EKG_UI_GRAFANA_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      labels: [traefik.enable=true,traefik.docker.network=modeco_overlay, traefik.http.services.package_ekg_grafana.loadbalancer.server.port=80, traefik.http.routers.package_ekg_grafana.entrypoints=conteco, traefik.http.routers.package_ekg_grafana.rule=PathPrefix("/package/ekg/grafana")]
# END SERVICE nginx.rewrite

volumes: {}
networks: {modeco_overlay: { external: true }, package_overlay: { external: true }}
